In [1]:
import numpy as np

### Task 0 - create_confusion.py

In [2]:
# Task 0 - create_confusion.py
def create_confusion_matrix(labels, logits):
    """
    Creates a confusion matrix:

    Inputs:
    labels -  one-hot numpy.ndarray of shape (m, classes) containing the
              correct labels for each data point
        m - number of data points
        classes - number of classes
    logits - one-hot numpy.ndarray (m, classes) containing predicted labels

    Returns:
    Confusion numpy.ndarray of shape (classes, classes) with
    row indices representing the correct labels and
    column indices representing the predicted labels
    """
    return np.matmul(labels.T, logits)

In [3]:
# 0-main.py
if __name__ == '__main__':
    lib = np.load('labels_logits.npz')
    labels = lib['labels']
    logits = lib['logits']

    np.set_printoptions(suppress=True)
    confusion = create_confusion_matrix(labels, logits)
    print(confusion)
    np.savez_compressed('confusion.npz', confusion=confusion)

[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631.  123.   33.  163.   60.]
 [  47.   32.   87.    1.   64.   83. 4607.    0.   29.    1.]
 [  26.   95.   75.    7.   58.   18.    1. 4682.   13.  200.]
 [  31.  153.   82.  174.   27.  179.   64.    7. 4003.  122.]
 [  48.   37.   39.   71.  220.   49.    8.  244.   46. 4226.]]


### Task 1 - sensitivity.py

In [4]:
# Task 1 - 1-sensitivity.py
#!/usr/bin/env python3
def sensitivity(confusion):
    """
    Calculates the sensitivity for each class in a confusion matrix

    Inputs:
    confusion - confusion numpy.ndarray of shape (classes, classes) where
        row indices represent the correct labels and
        column indices represent the predicted labels
        classes - the number of classes

    Returns:
    numpy.ndarray of shape (classes,) containing the sensitivity of each class
    """
    return np.diagonal(confusion) / np.sum(confusion, axis=1)

In [5]:
# 1-main.py
if __name__ == '__main__':
    confusion = np.load('confusion.npz')['confusion']

    np.set_printoptions(suppress=True)
    print(sensitivity(confusion))

[0.95316302 0.96759422 0.84299517 0.84493237 0.89277629 0.80581447
 0.93051909 0.9047343  0.82672449 0.84723336]


### Task 2 - precision.py

In [6]:
# Task 2 - 2-precision.py
def precision(confusion):
    """
    Calculates the Precision for each class in a confusion matrix

    Inputs:
    confusion - confusion numpy.ndarray of shape (classes, classes) where
        row indices represent the correct labels and
        column indices represent the predicted labels
        classes - the number of classes

    Returns:
    numpy.ndarray of shape (classes,) containing the precision of each class
    """
    return np.diagonal(confusion) / np.sum(confusion, axis=0)

In [7]:
# 2-main.py
if __name__ == '__main__':
    confusion = np.load('confusion.npz')['confusion']

    np.set_printoptions(suppress=True)
    print(precision(confusion))

[0.93033841 0.91020543 0.87359199 0.87264628 0.88494492 0.83298922
 0.90050821 0.90648596 0.86364617 0.84503099]


### Task 3 - specificity.py

In [10]:
# Task 3 - 3-specificity.py
def specificity(confusion):
    """
    Calculates the specificity for each class in a confusion matrix

    Inputs:
    confusion - confusion numpy.ndarray of shape (classes, classes) where
        row indices represent the correct labels and
        column indices represent the predicted labels
        classes - the number of classes

    Returns:
    numpy.ndarray of shape (classes,) containing the specificity of each class
    """

    all_instances = np.sum(confusion)
    true_positives = np.diag(confusion)
    predicted_positives = np.sum(confusion, axis=0)
    positives = np.sum(confusion, axis = 1)

    true_negatives = (all_instances - predicted_positives -
                      positives + true_positives)

    number_negatives = (all_instances - positives)

    true_negative_ratio = true_negatives / number_negatives

    return true_negative_ratio

In [11]:
# 3-main.py
if __name__ == '__main__':
    confusion = np.load('confusion.npz')['confusion']

    np.set_printoptions(suppress=True)
    print(specificity(confusion))

[0.99218958 0.98777131 0.9865429  0.98599078 0.98750582 0.98399789
 0.98870119 0.98922476 0.98600469 0.98278237]


### Task 4 - f1_score.py

In [13]:
# Task 4 - 4-f1_score.py
def f1_score(confusion):
    """
    Calculates the F1 score of a confusion matrix

    Inputs:
    confusion - confusion numpy.ndarray of shape (classes, classes) where
        row indices represent the correct labels and
        column indices represent the predicted labels
        classes - the number of classes

    Returns:
    numpy.ndarray of shape (classes,) containing the F1 score of each class
    """

    prec = precision(confusion)
    sens = sensitivity(confusion)

    f1 = 2 * (prec * sens) / (prec + sens)
    return f1

In [14]:
# 4-main.py
if __name__ == '__main__':
    confusion = np.load('confusion.npz')['confusion']

    np.set_printoptions(suppress=True)
    print(f1_score(confusion))

[0.94161242 0.93802288 0.8580209  0.85856574 0.88884336 0.81917654
 0.91526771 0.90560928 0.8447821  0.84613074]
