In [1]:
import numpy as np

### Task 0 - create_confusion.py

In [2]:
# Task 0 - create_confusion.py
def create_confusion_matrix(labels, logits):
    """
    Creates a confusion matrix:

    Inputs:
    labels -  one-hot numpy.ndarray of shape (m, classes) containing the
              correct labels for each data point
        m - number of data points
        classes - number of classes
    logits - one-hot numpy.ndarray (m, classes) containing predicted labels

    Returns:
    Confusion numpy.ndarray of shape (classes, classes) with
    row indices representing the correct labels and
    column indices representing the predicted labels
    """
    return np.matmul(labels.T, logits)

In [3]:
# 0-main.py
if __name__ == '__main__':
    lib = np.load('labels_logits.npz')
    labels = lib['labels']
    logits = lib['logits']

    np.set_printoptions(suppress=True)
    confusion = create_confusion_matrix(labels, logits)
    print(confusion)
    np.savez_compressed('confusion.npz', confusion=confusion)

[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631.  123.   33.  163.   60.]
 [  47.   32.   87.    1.   64.   83. 4607.    0.   29.    1.]
 [  26.   95.   75.    7.   58.   18.    1. 4682.   13.  200.]
 [  31.  153.   82.  174.   27.  179.   64.    7. 4003.  122.]
 [  48.   37.   39.   71.  220.   49.    8.  244.   46. 4226.]]


### Task 1 - sensitivity.py

In [4]:
# Task 1 - 1-sensitivity.py
#!/usr/bin/env python3
def sensitivity(confusion):
    """
    Calculates the sensitivity for each class in a confusion matrix

    Inputs:
    confusion - confusion numpy.ndarray of shape (classes, classes) where
        row indices represent the correct labels and
        column indices represent the predicted labels
        classes - the number of classes

    Returns:
    numpy.ndarray of shape (classes,) containing the sensitivity of each class
    """
    return np.diagonal(confusion) / np.sum(confusion, axis=1)

In [ ]:
# 1-main.py
if __name__ == '__main__':
    confusion = np.load('confusion.npz')['confusion']

    np.set_printoptions(suppress=True)
    print(sensitivity(confusion))